/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as JobsRunIdRouteImport } from './routes/jobs/$runId'
import { Route as ExperimentsExperimentNameRouteImport } from './routes/experiments/$experimentName'
import { Route as TagsKeyValueRouteImport } from './routes/tags/$key.$value'
import { Route as EvalsRunIdEvalIdRouteImport } from './routes/evals/$runId.$evalId'
import { Route as RunsRunIdSuiteSuiteRouteImport } from './routes/runs/$runId_.suite.$suite'
import { Route as RunsRunIdCategoryCategoryRouteImport } from './routes/runs/$runId_.category.$category'
import { Route as ProjectsProjectIdRunsRunIdRouteImport } from './routes/projects/$projectId_/runs/$runId'
import { Route as ProjectsProjectIdJobsRunIdRouteImport } from './routes/projects/$projectId_/jobs/$runId'
import { Route as ProjectsProjectIdExperimentsExperimentNameRouteImport } from './routes/projects/$projectId_/experiments/$experimentName'
import { Route as ProjectsProjectIdTagsKeyValueRouteImport } from './routes/projects/$projectId_/tags/$key.$value'
import { Route as ProjectsProjectIdEvalsRunIdEvalIdRouteImport } from './routes/projects/$projectId_/evals/$runId.$evalId'
import { Route as ProjectsProjectIdRunsRunIdSuiteSuiteRouteImport } from './routes/projects/$projectId_/runs/$runId_.suite.$suite'
import { Route as ProjectsProjectIdRunsRunIdCategoryCategoryRouteImport } from './routes/projects/$projectId_/runs/$runId_.category.$category'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRunIdRoute = JobsRunIdRouteImport.update({
  id: '/jobs/$runId',
  path: '/jobs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsExperimentNameRoute =
  ExperimentsExperimentNameRouteImport.update({
    id: '/experiments/$experimentName',
    path: '/experiments/$experimentName',
    getParentRoute: () => rootRouteImport,
  } as any)
const TagsKeyValueRoute = TagsKeyValueRouteImport.update({
  id: '/tags/$key/$value',
  path: '/tags/$key/$value',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRunIdEvalIdRoute = EvalsRunIdEvalIdRouteImport.update({
  id: '/evals/$runId/$evalId',
  path: '/evals/$runId/$evalId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdSuiteSuiteRoute = RunsRunIdSuiteSuiteRouteImport.update({
  id: '/runs/$runId_/suite/$suite',
  path: '/runs/$runId/suite/$suite',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdCategoryCategoryRoute =
  RunsRunIdCategoryCategoryRouteImport.update({
    id: '/runs/$runId_/category/$category',
    path: '/runs/$runId/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRunsRunIdRoute =
  ProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/projects/$projectId_/runs/$runId',
    path: '/projects/$projectId/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdJobsRunIdRoute =
  ProjectsProjectIdJobsRunIdRouteImport.update({
    id: '/projects/$projectId_/jobs/$runId',
    path: '/projects/$projectId/jobs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdExperimentsExperimentNameRoute =
  ProjectsProjectIdExperimentsExperimentNameRouteImport.update({
    id: '/projects/$projectId_/experiments/$experimentName',
    path: '/projects/$projectId/experiments/$experimentName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdTagsKeyValueRoute =
  ProjectsProjectIdTagsKeyValueRouteImport.update({
    id: '/projects/$projectId_/tags/$key/$value',
    path: '/projects/$projectId/tags/$key/$value',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdEvalsRunIdEvalIdRoute =
  ProjectsProjectIdEvalsRunIdEvalIdRouteImport.update({
    id: '/projects/$projectId_/evals/$runId/$evalId',
    path: '/projects/$projectId/evals/$runId/$evalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRunsRunIdSuiteSuiteRoute =
  ProjectsProjectIdRunsRunIdSuiteSuiteRouteImport.update({
    id: '/projects/$projectId_/runs/$runId_/suite/$suite',
    path: '/projects/$projectId/runs/$runId/suite/$suite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdRunsRunIdCategoryCategoryRoute =
  ProjectsProjectIdRunsRunIdCategoryCategoryRouteImport.update({
    id: '/projects/$projectId_/runs/$runId_/category/$category',
    path: '/projects/$projectId/runs/$runId/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/experiments/$experimentName': typeof ExperimentsExperimentNameRoute
  '/jobs/$runId': typeof JobsRunIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals/$runId/$evalId': typeof EvalsRunIdEvalIdRoute
  '/tags/$key/$value': typeof TagsKeyValueRoute
  '/projects/$projectId/experiments/$experimentName': typeof ProjectsProjectIdExperimentsExperimentNameRoute
  '/projects/$projectId/jobs/$runId': typeof ProjectsProjectIdJobsRunIdRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/runs/$runId/category/$category': typeof RunsRunIdCategoryCategoryRoute
  '/runs/$runId/suite/$suite': typeof RunsRunIdSuiteSuiteRoute
  '/projects/$projectId/evals/$runId/$evalId': typeof ProjectsProjectIdEvalsRunIdEvalIdRoute
  '/projects/$projectId/tags/$key/$value': typeof ProjectsProjectIdTagsKeyValueRoute
  '/projects/$projectId/runs/$runId/category/$category': typeof ProjectsProjectIdRunsRunIdCategoryCategoryRoute
  '/projects/$projectId/runs/$runId/suite/$suite': typeof ProjectsProjectIdRunsRunIdSuiteSuiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/experiments/$experimentName': typeof ExperimentsExperimentNameRoute
  '/jobs/$runId': typeof JobsRunIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals/$runId/$evalId': typeof EvalsRunIdEvalIdRoute
  '/tags/$key/$value': typeof TagsKeyValueRoute
  '/projects/$projectId/experiments/$experimentName': typeof ProjectsProjectIdExperimentsExperimentNameRoute
  '/projects/$projectId/jobs/$runId': typeof ProjectsProjectIdJobsRunIdRoute
  '/projects/$projectId/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/runs/$runId/category/$category': typeof RunsRunIdCategoryCategoryRoute
  '/runs/$runId/suite/$suite': typeof RunsRunIdSuiteSuiteRoute
  '/projects/$projectId/evals/$runId/$evalId': typeof ProjectsProjectIdEvalsRunIdEvalIdRoute
  '/projects/$projectId/tags/$key/$value': typeof ProjectsProjectIdTagsKeyValueRoute
  '/projects/$projectId/runs/$runId/category/$category': typeof ProjectsProjectIdRunsRunIdCategoryCategoryRoute
  '/projects/$projectId/runs/$runId/suite/$suite': typeof ProjectsProjectIdRunsRunIdSuiteSuiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/experiments/$experimentName': typeof ExperimentsExperimentNameRoute
  '/jobs/$runId': typeof JobsRunIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals/$runId/$evalId': typeof EvalsRunIdEvalIdRoute
  '/tags/$key/$value': typeof TagsKeyValueRoute
  '/projects/$projectId_/experiments/$experimentName': typeof ProjectsProjectIdExperimentsExperimentNameRoute
  '/projects/$projectId_/jobs/$runId': typeof ProjectsProjectIdJobsRunIdRoute
  '/projects/$projectId_/runs/$runId': typeof ProjectsProjectIdRunsRunIdRoute
  '/runs/$runId_/category/$category': typeof RunsRunIdCategoryCategoryRoute
  '/runs/$runId_/suite/$suite': typeof RunsRunIdSuiteSuiteRoute
  '/projects/$projectId_/evals/$runId/$evalId': typeof ProjectsProjectIdEvalsRunIdEvalIdRoute
  '/projects/$projectId_/tags/$key/$value': typeof ProjectsProjectIdTagsKeyValueRoute
  '/projects/$projectId_/runs/$runId_/category/$category': typeof ProjectsProjectIdRunsRunIdCategoryCategoryRoute
  '/projects/$projectId_/runs/$runId_/suite/$suite': typeof ProjectsProjectIdRunsRunIdSuiteSuiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/experiments/$experimentName'
    | '/jobs/$runId'
    | '/projects/$projectId'
    | '/runs/$runId'
    | '/evals/$runId/$evalId'
    | '/tags/$key/$value'
    | '/projects/$projectId/experiments/$experimentName'
    | '/projects/$projectId/jobs/$runId'
    | '/projects/$projectId/runs/$runId'
    | '/runs/$runId/category/$category'
    | '/runs/$runId/suite/$suite'
    | '/projects/$projectId/evals/$runId/$evalId'
    | '/projects/$projectId/tags/$key/$value'
    | '/projects/$projectId/runs/$runId/category/$category'
    | '/projects/$projectId/runs/$runId/suite/$suite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/experiments/$experimentName'
    | '/jobs/$runId'
    | '/projects/$projectId'
    | '/runs/$runId'
    | '/evals/$runId/$evalId'
    | '/tags/$key/$value'
    | '/projects/$projectId/experiments/$experimentName'
    | '/projects/$projectId/jobs/$runId'
    | '/projects/$projectId/runs/$runId'
    | '/runs/$runId/category/$category'
    | '/runs/$runId/suite/$suite'
    | '/projects/$projectId/evals/$runId/$evalId'
    | '/projects/$projectId/tags/$key/$value'
    | '/projects/$projectId/runs/$runId/category/$category'
    | '/projects/$projectId/runs/$runId/suite/$suite'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/experiments/$experimentName'
    | '/jobs/$runId'
    | '/projects/$projectId'
    | '/runs/$runId'
    | '/evals/$runId/$evalId'
    | '/tags/$key/$value'
    | '/projects/$projectId_/experiments/$experimentName'
    | '/projects/$projectId_/jobs/$runId'
    | '/projects/$projectId_/runs/$runId'
    | '/runs/$runId_/category/$category'
    | '/runs/$runId_/suite/$suite'
    | '/projects/$projectId_/evals/$runId/$evalId'
    | '/projects/$projectId_/tags/$key/$value'
    | '/projects/$projectId_/runs/$runId_/category/$category'
    | '/projects/$projectId_/runs/$runId_/suite/$suite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ExperimentsExperimentNameRoute: typeof ExperimentsExperimentNameRoute
  JobsRunIdRoute: typeof JobsRunIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  EvalsRunIdEvalIdRoute: typeof EvalsRunIdEvalIdRoute
  TagsKeyValueRoute: typeof TagsKeyValueRoute
  ProjectsProjectIdExperimentsExperimentNameRoute: typeof ProjectsProjectIdExperimentsExperimentNameRoute
  ProjectsProjectIdJobsRunIdRoute: typeof ProjectsProjectIdJobsRunIdRoute
  ProjectsProjectIdRunsRunIdRoute: typeof ProjectsProjectIdRunsRunIdRoute
  RunsRunIdCategoryCategoryRoute: typeof RunsRunIdCategoryCategoryRoute
  RunsRunIdSuiteSuiteRoute: typeof RunsRunIdSuiteSuiteRoute
  ProjectsProjectIdEvalsRunIdEvalIdRoute: typeof ProjectsProjectIdEvalsRunIdEvalIdRoute
  ProjectsProjectIdTagsKeyValueRoute: typeof ProjectsProjectIdTagsKeyValueRoute
  ProjectsProjectIdRunsRunIdCategoryCategoryRoute: typeof ProjectsProjectIdRunsRunIdCategoryCategoryRoute
  ProjectsProjectIdRunsRunIdSuiteSuiteRoute: typeof ProjectsProjectIdRunsRunIdSuiteSuiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$runId': {
      id: '/jobs/$runId'
      path: '/jobs/$runId'
      fullPath: '/jobs/$runId'
      preLoaderRoute: typeof JobsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$experimentName': {
      id: '/experiments/$experimentName'
      path: '/experiments/$experimentName'
      fullPath: '/experiments/$experimentName'
      preLoaderRoute: typeof ExperimentsExperimentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$key/$value': {
      id: '/tags/$key/$value'
      path: '/tags/$key/$value'
      fullPath: '/tags/$key/$value'
      preLoaderRoute: typeof TagsKeyValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/$runId/$evalId': {
      id: '/evals/$runId/$evalId'
      path: '/evals/$runId/$evalId'
      fullPath: '/evals/$runId/$evalId'
      preLoaderRoute: typeof EvalsRunIdEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId_/suite/$suite': {
      id: '/runs/$runId_/suite/$suite'
      path: '/runs/$runId/suite/$suite'
      fullPath: '/runs/$runId/suite/$suite'
      preLoaderRoute: typeof RunsRunIdSuiteSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId_/category/$category': {
      id: '/runs/$runId_/category/$category'
      path: '/runs/$runId/category/$category'
      fullPath: '/runs/$runId/category/$category'
      preLoaderRoute: typeof RunsRunIdCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/runs/$runId': {
      id: '/projects/$projectId_/runs/$runId'
      path: '/projects/$projectId/runs/$runId'
      fullPath: '/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/jobs/$runId': {
      id: '/projects/$projectId_/jobs/$runId'
      path: '/projects/$projectId/jobs/$runId'
      fullPath: '/projects/$projectId/jobs/$runId'
      preLoaderRoute: typeof ProjectsProjectIdJobsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/experiments/$experimentName': {
      id: '/projects/$projectId_/experiments/$experimentName'
      path: '/projects/$projectId/experiments/$experimentName'
      fullPath: '/projects/$projectId/experiments/$experimentName'
      preLoaderRoute: typeof ProjectsProjectIdExperimentsExperimentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/tags/$key/$value': {
      id: '/projects/$projectId_/tags/$key/$value'
      path: '/projects/$projectId/tags/$key/$value'
      fullPath: '/projects/$projectId/tags/$key/$value'
      preLoaderRoute: typeof ProjectsProjectIdTagsKeyValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/evals/$runId/$evalId': {
      id: '/projects/$projectId_/evals/$runId/$evalId'
      path: '/projects/$projectId/evals/$runId/$evalId'
      fullPath: '/projects/$projectId/evals/$runId/$evalId'
      preLoaderRoute: typeof ProjectsProjectIdEvalsRunIdEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/runs/$runId_/suite/$suite': {
      id: '/projects/$projectId_/runs/$runId_/suite/$suite'
      path: '/projects/$projectId/runs/$runId/suite/$suite'
      fullPath: '/projects/$projectId/runs/$runId/suite/$suite'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdSuiteSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/runs/$runId_/category/$category': {
      id: '/projects/$projectId_/runs/$runId_/category/$category'
      path: '/projects/$projectId/runs/$runId/category/$category'
      fullPath: '/projects/$projectId/runs/$runId/category/$category'
      preLoaderRoute: typeof ProjectsProjectIdRunsRunIdCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ExperimentsExperimentNameRoute: ExperimentsExperimentNameRoute,
  JobsRunIdRoute: JobsRunIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  EvalsRunIdEvalIdRoute: EvalsRunIdEvalIdRoute,
  TagsKeyValueRoute: TagsKeyValueRoute,
  ProjectsProjectIdExperimentsExperimentNameRoute:
    ProjectsProjectIdExperimentsExperimentNameRoute,
  ProjectsProjectIdJobsRunIdRoute: ProjectsProjectIdJobsRunIdRoute,
  ProjectsProjectIdRunsRunIdRoute: ProjectsProjectIdRunsRunIdRoute,
  RunsRunIdCategoryCategoryRoute: RunsRunIdCategoryCategoryRoute,
  RunsRunIdSuiteSuiteRoute: RunsRunIdSuiteSuiteRoute,
  ProjectsProjectIdEvalsRunIdEvalIdRoute:
    ProjectsProjectIdEvalsRunIdEvalIdRoute,
  ProjectsProjectIdTagsKeyValueRoute: ProjectsProjectIdTagsKeyValueRoute,
  ProjectsProjectIdRunsRunIdCategoryCategoryRoute:
    ProjectsProjectIdRunsRunIdCategoryCategoryRoute,
  ProjectsProjectIdRunsRunIdSuiteSuiteRoute:
    ProjectsProjectIdRunsRunIdSuiteSuiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
