/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as JobsRunIdRouteImport } from './routes/jobs/$runId'
import { Route as ExperimentsExperimentNameRouteImport } from './routes/experiments/$experimentName'
import { Route as BenchmarksBenchmarkIdRouteImport } from './routes/benchmarks/$benchmarkId'
import { Route as EvalsRunIdEvalIdRouteImport } from './routes/evals/$runId.$evalId'
import { Route as RunsRunIdSuiteSuiteRouteImport } from './routes/runs/$runId_.suite.$suite'
import { Route as RunsRunIdCategoryCategoryRouteImport } from './routes/runs/$runId_.category.$category'
import { Route as BenchmarksBenchmarkIdRunsRunIdRouteImport } from './routes/benchmarks/$benchmarkId_/runs/$runId'
import { Route as BenchmarksBenchmarkIdEvalsRunIdEvalIdRouteImport } from './routes/benchmarks/$benchmarkId_/evals/$runId.$evalId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRunIdRoute = JobsRunIdRouteImport.update({
  id: '/jobs/$runId',
  path: '/jobs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsExperimentNameRoute =
  ExperimentsExperimentNameRouteImport.update({
    id: '/experiments/$experimentName',
    path: '/experiments/$experimentName',
    getParentRoute: () => rootRouteImport,
  } as any)
const BenchmarksBenchmarkIdRoute = BenchmarksBenchmarkIdRouteImport.update({
  id: '/benchmarks/$benchmarkId',
  path: '/benchmarks/$benchmarkId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalsRunIdEvalIdRoute = EvalsRunIdEvalIdRouteImport.update({
  id: '/evals/$runId/$evalId',
  path: '/evals/$runId/$evalId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdSuiteSuiteRoute = RunsRunIdSuiteSuiteRouteImport.update({
  id: '/runs/$runId_/suite/$suite',
  path: '/runs/$runId/suite/$suite',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdCategoryCategoryRoute =
  RunsRunIdCategoryCategoryRouteImport.update({
    id: '/runs/$runId_/category/$category',
    path: '/runs/$runId/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const BenchmarksBenchmarkIdRunsRunIdRoute =
  BenchmarksBenchmarkIdRunsRunIdRouteImport.update({
    id: '/benchmarks/$benchmarkId_/runs/$runId',
    path: '/benchmarks/$benchmarkId/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BenchmarksBenchmarkIdEvalsRunIdEvalIdRoute =
  BenchmarksBenchmarkIdEvalsRunIdEvalIdRouteImport.update({
    id: '/benchmarks/$benchmarkId_/evals/$runId/$evalId',
    path: '/benchmarks/$benchmarkId/evals/$runId/$evalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/benchmarks/$benchmarkId': typeof BenchmarksBenchmarkIdRoute
  '/experiments/$experimentName': typeof ExperimentsExperimentNameRoute
  '/jobs/$runId': typeof JobsRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals/$runId/$evalId': typeof EvalsRunIdEvalIdRoute
  '/benchmarks/$benchmarkId/runs/$runId': typeof BenchmarksBenchmarkIdRunsRunIdRoute
  '/runs/$runId/category/$category': typeof RunsRunIdCategoryCategoryRoute
  '/runs/$runId/suite/$suite': typeof RunsRunIdSuiteSuiteRoute
  '/benchmarks/$benchmarkId/evals/$runId/$evalId': typeof BenchmarksBenchmarkIdEvalsRunIdEvalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/benchmarks/$benchmarkId': typeof BenchmarksBenchmarkIdRoute
  '/experiments/$experimentName': typeof ExperimentsExperimentNameRoute
  '/jobs/$runId': typeof JobsRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals/$runId/$evalId': typeof EvalsRunIdEvalIdRoute
  '/benchmarks/$benchmarkId/runs/$runId': typeof BenchmarksBenchmarkIdRunsRunIdRoute
  '/runs/$runId/category/$category': typeof RunsRunIdCategoryCategoryRoute
  '/runs/$runId/suite/$suite': typeof RunsRunIdSuiteSuiteRoute
  '/benchmarks/$benchmarkId/evals/$runId/$evalId': typeof BenchmarksBenchmarkIdEvalsRunIdEvalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/benchmarks/$benchmarkId': typeof BenchmarksBenchmarkIdRoute
  '/experiments/$experimentName': typeof ExperimentsExperimentNameRoute
  '/jobs/$runId': typeof JobsRunIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/evals/$runId/$evalId': typeof EvalsRunIdEvalIdRoute
  '/benchmarks/$benchmarkId_/runs/$runId': typeof BenchmarksBenchmarkIdRunsRunIdRoute
  '/runs/$runId_/category/$category': typeof RunsRunIdCategoryCategoryRoute
  '/runs/$runId_/suite/$suite': typeof RunsRunIdSuiteSuiteRoute
  '/benchmarks/$benchmarkId_/evals/$runId/$evalId': typeof BenchmarksBenchmarkIdEvalsRunIdEvalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/benchmarks/$benchmarkId'
    | '/experiments/$experimentName'
    | '/jobs/$runId'
    | '/runs/$runId'
    | '/evals/$runId/$evalId'
    | '/benchmarks/$benchmarkId/runs/$runId'
    | '/runs/$runId/category/$category'
    | '/runs/$runId/suite/$suite'
    | '/benchmarks/$benchmarkId/evals/$runId/$evalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/benchmarks/$benchmarkId'
    | '/experiments/$experimentName'
    | '/jobs/$runId'
    | '/runs/$runId'
    | '/evals/$runId/$evalId'
    | '/benchmarks/$benchmarkId/runs/$runId'
    | '/runs/$runId/category/$category'
    | '/runs/$runId/suite/$suite'
    | '/benchmarks/$benchmarkId/evals/$runId/$evalId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/benchmarks/$benchmarkId'
    | '/experiments/$experimentName'
    | '/jobs/$runId'
    | '/runs/$runId'
    | '/evals/$runId/$evalId'
    | '/benchmarks/$benchmarkId_/runs/$runId'
    | '/runs/$runId_/category/$category'
    | '/runs/$runId_/suite/$suite'
    | '/benchmarks/$benchmarkId_/evals/$runId/$evalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  BenchmarksBenchmarkIdRoute: typeof BenchmarksBenchmarkIdRoute
  ExperimentsExperimentNameRoute: typeof ExperimentsExperimentNameRoute
  JobsRunIdRoute: typeof JobsRunIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  EvalsRunIdEvalIdRoute: typeof EvalsRunIdEvalIdRoute
  BenchmarksBenchmarkIdRunsRunIdRoute: typeof BenchmarksBenchmarkIdRunsRunIdRoute
  RunsRunIdCategoryCategoryRoute: typeof RunsRunIdCategoryCategoryRoute
  RunsRunIdSuiteSuiteRoute: typeof RunsRunIdSuiteSuiteRoute
  BenchmarksBenchmarkIdEvalsRunIdEvalIdRoute: typeof BenchmarksBenchmarkIdEvalsRunIdEvalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$runId': {
      id: '/jobs/$runId'
      path: '/jobs/$runId'
      fullPath: '/jobs/$runId'
      preLoaderRoute: typeof JobsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$experimentName': {
      id: '/experiments/$experimentName'
      path: '/experiments/$experimentName'
      fullPath: '/experiments/$experimentName'
      preLoaderRoute: typeof ExperimentsExperimentNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/$benchmarkId': {
      id: '/benchmarks/$benchmarkId'
      path: '/benchmarks/$benchmarkId'
      fullPath: '/benchmarks/$benchmarkId'
      preLoaderRoute: typeof BenchmarksBenchmarkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals/$runId/$evalId': {
      id: '/evals/$runId/$evalId'
      path: '/evals/$runId/$evalId'
      fullPath: '/evals/$runId/$evalId'
      preLoaderRoute: typeof EvalsRunIdEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId_/suite/$suite': {
      id: '/runs/$runId_/suite/$suite'
      path: '/runs/$runId/suite/$suite'
      fullPath: '/runs/$runId/suite/$suite'
      preLoaderRoute: typeof RunsRunIdSuiteSuiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId_/category/$category': {
      id: '/runs/$runId_/category/$category'
      path: '/runs/$runId/category/$category'
      fullPath: '/runs/$runId/category/$category'
      preLoaderRoute: typeof RunsRunIdCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/$benchmarkId_/runs/$runId': {
      id: '/benchmarks/$benchmarkId_/runs/$runId'
      path: '/benchmarks/$benchmarkId/runs/$runId'
      fullPath: '/benchmarks/$benchmarkId/runs/$runId'
      preLoaderRoute: typeof BenchmarksBenchmarkIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/$benchmarkId_/evals/$runId/$evalId': {
      id: '/benchmarks/$benchmarkId_/evals/$runId/$evalId'
      path: '/benchmarks/$benchmarkId/evals/$runId/$evalId'
      fullPath: '/benchmarks/$benchmarkId/evals/$runId/$evalId'
      preLoaderRoute: typeof BenchmarksBenchmarkIdEvalsRunIdEvalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  BenchmarksBenchmarkIdRoute: BenchmarksBenchmarkIdRoute,
  ExperimentsExperimentNameRoute: ExperimentsExperimentNameRoute,
  JobsRunIdRoute: JobsRunIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  EvalsRunIdEvalIdRoute: EvalsRunIdEvalIdRoute,
  BenchmarksBenchmarkIdRunsRunIdRoute: BenchmarksBenchmarkIdRunsRunIdRoute,
  RunsRunIdCategoryCategoryRoute: RunsRunIdCategoryCategoryRoute,
  RunsRunIdSuiteSuiteRoute: RunsRunIdSuiteSuiteRoute,
  BenchmarksBenchmarkIdEvalsRunIdEvalIdRoute:
    BenchmarksBenchmarkIdEvalsRunIdEvalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
